---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  #requirements_path: requirements.yml
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

platforms:
  # - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    driver:
      network:
        - ["private_network", { ip: "172.29.129.179" }]
        - ["forwarded_port", {guest: 80, host: 80}]
        - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
